version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:latest

    steps:
      - checkout

      - run:
          name: Build Docker Image
          command: |
            docker build -t project -f ../Dockerfile.dev .

      - run:
          name: Run Tests
          command: |
            docker run project npm run test -- --coverage
